### ISSUE TITLE
Send a video stream from C# via webRTC

### ISSUE THREAD

**Issue by DamienDoumer** [ttustonic/GStreamerSharpSamples#1]
I'm opening this issue mainly cause I don't know where to ask this question apart from here.

So, I have an android app and I capture the device's screen, create a video stream and I wish to send it via WebRTC.  Does this library permit me to do that ? I looked at the examples and none does this, is there a resource or a link to an example similar to this ? be it desktop, windows or linux streaming... Since most of the webrtc implementation I find online use "GetUserMedia"... I'm kind of confused. Sorry if my question sounds silly. But please I really need answers.

**Comment by ttustonic** [comment]
Hello
It's been too long since I've played with GStreamer, so I forgot most of the things, sadly.
However, I believe you should be able to capture screen using ximagesrc on Linux and dx9screencapsrc on Windows.
You can then send this stream instead of camera, like in the WebRTC examples.

Here's an example of screen capture in Linux
https://stackoverflow.com/questions/33747500/using-gstreamer-to-capture-screen-and-show-it-in-a-window

Sorry, I can't help you more at this moment.

**Comment by DamienDoumer** [comment]
thanks
